name: Weather Update

on:
  schedule:
    - cron: '0/1 * * * *'  # Schedule to run at 8 am and 8 pm UTC

jobs:
    job_name:

     runs-on: windows-latest

     steps:

      - name: Run Python Script
        run:  Webscraping= Weather Scrapper GitHub.ipynb
